name: ItemBrag
api: 4.0.0
version: 1.4.0
main: TPE\ItemBrag\Main
author: TPE

commands:
  brag:
    description: "Brag to others about the item in your hand!"
    permission: itembrag.brag.allow

permissions:

  itembrag.brag.allow:
    description: Allows players to brag using /brag.
    default: op

  itembrag.allow.enchants:
    description: Allows players to brag about items with enchants on.
    default: op
