name: ItemBrag
api: 3.14.0
version: 1.3.0
main: TPE\ItemBrag\Main
author: TPE

commands:
  brag:
    description: "Brag to others about the item in your hand!"

permissions:

  itembrag.brag.allow:
    description: Allows players to brag using /brag.
    default: op

  itembrag.allow.enchants:
    description: Allows players to brag about items with enchants on.
    default: op
