# Set this to true if you wish to disable /brag without uninstalling the plugin

brag-disabled: false

# Message sent to player if brag-feature-disabled is set to true

brag-feature-disabled-message: "§cThis command is currently disabled!"

# Message sent to player if they run /brag and their hand is empty

message-sent-to-player-when-hand-is-empty: "§cYou must hold an item while running this command!"

# Message sent to player if they lack the permissions to brag

no-perms-message: "§cYou do not have permission to use this command!"

# Message sent to player if they lack the permission to brag about items with enchants on

no-perms-message-enchants: "§cYou do not have permission to brag about items with enchants on!"